insert into member(ID,NAME,PHONE_NUMBER,EMAIL_ADDRESS) values (1,'Fahad Shami','0404929999','fahadshami@someDomain.com');
insert into member(ID,NAME,PHONE_NUMBER,EMAIL_ADDRESS) values (2,'Min Pan','0406822665','panmin@someDomain.com');
insert into member(ID,NAME,PHONE_NUMBER,EMAIL_ADDRESS) values (3,'Chris Johnson','0407985998','johnChris@someDomain.com');
insert into member(ID,NAME,PHONE_NUMBER,EMAIL_ADDRESS) values (4,'Mitchell Adam','0405123321','adam@someDomain.com');
insert into member(ID,NAME,PHONE_NUMBER,EMAIL_ADDRESS) values (5,'Bec McDonald','0406321654','bec@someDomain.com');
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (1,'Effective Java','Joshua Bloch','123-321-555',1);
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (2,'SCJP','Scott Selikoff','444-202-544',1);
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (3,'EarthSea','Ursula Guin','673-991-588',3);
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (4,'Pride and Prejudice','Jane Austen','342-567-124',3);
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (5,'Core Java','Cay S.Hortsmann','395-409-450',2);
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (6,'Resurrection','Leo Tolstoy','111-333-124',3);
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (7,'Frankenstein','Mary Shelley','543-406-135',null);
insert into Book(BOOK_ID,TITLE,AUTHOR,ISBN,MEMBER_ID) values (8,'Money','Martin Amis','678-184-086',null);